#!/usr/bin/env python3
"""
Patches a MuJoCo MJCF robot XML file (as generated by onshape-to-robot) with:
  1. Updated default class definitions:
       - Adds 'collision_wheel' class (contype=2 / conaffinity=1, ground-only)
       - Adds contype/conaffinity to 'collision' class (contype=4 / conaffinity=5)
  2. Custom capsule geoms inserted into each wheel body for collision detection
  3. Contact pairs at the end for anisotropic (omni-wheel) friction handling

Usage:
    python robot_patcher.py [input.xml [output.xml]]

If only input is given, the file is patched in place.
If no arguments are given, robot.xml in the same directory is patched in place.
"""

import re
import sys
import os


def patch_default_classes(content: str) -> str:
    """Replace the bare 'collision' default class with collision_wheel + collision."""
    pattern = re.compile(
        r'(\s+)<default class="collision">\n'
        r'(\s+)<geom group="3"/>\n'
        r'(\s+)</default>'
    )

    def replacement(m: re.Match) -> str:
        outer = m.group(1)  # indentation of <default class="collision">
        inner = m.group(2)  # indentation of <geom ...>
        return (
            f'{outer}<!-- Wheel are in contype 2, they collide ground only -->\n'
            f'{outer}<default class="collision_wheel">\n'
            f'{inner}<geom group="3" contype="2" conaffinity="1"/>\n'
            f'{outer}</default>\n'
            f'{outer}<!-- All other collision geoms are in contype 4, they collide themself and the ground-->\n'
            f'{outer}<default class="collision">\n'
            f'{inner}<geom group="3" contype="4" conaffinity="5"/>\n'
            f'{outer}</default>'
        )

    result, n = pattern.subn(replacement, content)
    if n == 0:
        print("WARNING: could not find '<default class=\"collision\">' block to patch.", file=sys.stderr)
    return result


def patch_wheel_capsules(content: str) -> str:
    """Insert a capsule geom into each wheel body right after its hinge joint."""
    for i in range(1, 4):
        joint_name = f'wheel{i}'
        capsule_name = f'wheel{i}_capsule'

        pattern = re.compile(
            rf'(\s+)<joint axis="0 0 1" name="{re.escape(joint_name)}" type="hinge"/>'
        )

        def replacement(m: re.Match, cn: str = capsule_name) -> str:
            indent = m.group(1)
            return (
                f'{m.group(0)}\n'
                f'{indent}<!-- Custom capsule -->\n'
                f'{indent}<geom name="{cn}" pos="0 0 -0.01" type="capsule"'
                f' size="0.035 0.0001" zaxis="0 0 1" class="collision_wheel" />'
            )

        result, n = pattern.subn(replacement, content)
        if n == 0:
            print(f"WARNING: could not find joint '{joint_name}' to insert capsule.", file=sys.stderr)
        content = result

    return content


def patch_contact_pairs(content: str) -> str:
    """Insert a <contact> section with anisotropic friction pairs before <equality/>."""
    contact_block = (
        '\n\n  <contact>\n'
        '    <pair geom1="floor" geom2="wheel1_capsule" condim="3" friction="0.1 1.0 0.005 0.0001 0.0001"/>\n'
        '    <pair geom1="floor" geom2="wheel2_capsule" condim="3" friction="0.1 1.0 0.005 0.0001 0.0001"/>\n'
        '    <pair geom1="floor" geom2="wheel3_capsule" condim="3" friction="0.1 1.0 0.005 0.0001 0.0001"/>\n'
        '  </contact>\n'
    )

    # Try inserting before <equality/>
    marker = '  <equality/>'
    if marker in content:
        return content.replace(marker, contact_block + '\n' + marker, 1)

    # Fallback: insert before </mujoco>
    if '</mujoco>' in content:
        print("WARNING: '<equality/>' not found; inserting contact block before '</mujoco>'.", file=sys.stderr)
        return content.replace('</mujoco>', contact_block + '\n</mujoco>', 1)

    print("WARNING: could not find a suitable location to insert contact pairs.", file=sys.stderr)
    return content


def patch(content: str) -> str:
    content = patch_default_classes(content)
    content = patch_wheel_capsules(content)
    content = patch_contact_pairs(content)
    return content


def main() -> None:
    script_dir = os.path.dirname(os.path.abspath(__file__))

    if len(sys.argv) == 1:
        input_file = os.path.join(script_dir, 'robot.xml')
        output_file = input_file
    elif len(sys.argv) == 2:
        input_file = sys.argv[1]
        output_file = input_file
    else:
        input_file = sys.argv[1]
        output_file = sys.argv[2]

    with open(input_file, 'r') as f:
        content = f.read()

    patched = patch(content)

    with open(output_file, 'w') as f:
        f.write(patched)

    action = 'in place' if input_file == output_file else f'-> {output_file}'
    print(f"Patched {input_file} {action}")


if __name__ == '__main__':
    main()
